title: Recept

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ""
      type: recipe
    values:
      layout: recipe
  - scope:
      path: ""
    values:
      layout: default
