title: Recept

baseurl: /recipes

theme: just-the-docs

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: page
  - scope:
      path: ""
    values:
      layout: default
