title: Recept
baseurl: /recipes

collections:
  recipes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe

theme: just-the-docs
logo: /assets/images/logo_340x340.png

just_the_docs:
  collections:
    recipes:
